title: portfólio de projetos - Pablo Aguiar Raposo
description: > # this means to ignore newlines until "baseurl:"
  Olá! SOu Pablo Aguiar Raposo e esse é o meu portfólio de projetos em Data Science
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pablo Aguiar Raposo # add your name
author-img: pablo-aguiar.JPG # add your photo
about-author: Bem vindo ao meu portfólio de data science! Colocarei aqui meus projetos conforme os for executando. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: Pablo-aguiarr # add your Github handle
social-linkedin: pablo-aguiar-raposo-71b6b5139 # add your Linkedin handle
social-email: pabloaguiar92@hotmail.com # add your Email address

# Disqus
discus-identifier: pablo # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

